1.元素级别的计算

（1）定义一个新数组arr11,用arange()函数和reshape()函数创建一个1~12组成的4*3的矩阵

In [1]:
import numpy as np
arr11 = 5-np.arange(1,13).reshape(4,3)
arr11

array([[ 4,  3,  2],
       [ 1,  0, -1],
       [-2, -3, -4],
       [-5, -6, -7]])

(2) 用**表示乘方，对arr11中的每个元素进行平方。计算结果如下:


In [2]:
arr11**2

array([[16,  9,  4],
       [ 1,  0,  1],
       [ 4,  9, 16],
       [25, 36, 49]], dtype=int32)

(3) 用np.sqrt() 对arr11中的每个元素开根号求值

In [3]:
np.sqrt(arr11)

<ipython-input-3-8c87c891600c>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr11)


array([[2.        , 1.73205081, 1.41421356],
       [1.        , 0.        ,        nan],
       [       nan,        nan,        nan],
       [       nan,        nan,        nan]])

发现出现了"nan"值，这是因为在arr11中有的元素是负值，负值不能开根。

（4）以e为底，arr11中的每个元素为指数，求值：


In [4]:
np.exp(arr11)

array([[5.45981500e+01, 2.00855369e+01, 7.38905610e+00],
       [2.71828183e+00, 1.00000000e+00, 3.67879441e-01],
       [1.35335283e-01, 4.97870684e-02, 1.83156389e-02],
       [6.73794700e-03, 2.47875218e-03, 9.11881966e-04]])

(5)求对数，用np.log()函数：

In [5]:
np.log(arr11)

<ipython-input-5-bb63112e68ba>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr11)
<ipython-input-5-bb63112e68ba>:1: RuntimeWarning: invalid value encountered in log
  np.log(arr11)


array([[1.38629436, 1.09861229, 0.69314718],
       [0.        ,       -inf,        nan],
       [       nan,        nan,        nan],
       [       nan,        nan,        nan]])

(6) 利用np.abs()函数对arr11中的每个元素进行求和

In [6]:
np.abs(arr11)

array([[4, 3, 2],
       [1, 0, 1],
       [2, 3, 4],
       [5, 6, 7]])

2、统计运算函数

（1） np.sum()
利用np.sum()函数对数组中的元素进行求和。

若想对数组中的每一列求和，在括号中加入参数 axis =0, 如果需要对行求和，那么将0改为1即可。



In [7]:
np.sum(arr11)

-18

In [8]:
np.sum(arr11,axis=0)

array([ -2,  -6, -10])

In [9]:
np.sum(arr11,axis=1)

array([  9,   0,  -9, -18])

(2) np.cumsum()

利用np.cumsum()累计和，注意：求数组arr11中的元素的累计和的顺序是“从上到下，从左到右”，最终得到结果：

同样，若想要对数组中的每一列求累计和，在括号中加入参数 axis=0,如果需要对行求累计和，那么将改为1即可。

In [10]:
np.cumsum(arr11)

array([  4,   7,   9,  10,  10,   9,   7,   4,   0,  -5, -11, -18],
      dtype=int32)

In [11]:
np.cumsum(arr11,axis=0)

array([[  4,   3,   2],
       [  5,   3,   1],
       [  3,   0,  -3],
       [ -2,  -6, -10]], dtype=int32)

In [12]:
np.cumsum(arr11,axis=1)

array([[  4,   7,   9],
       [  1,   1,   0],
       [ -2,  -5,  -9],
       [ -5, -11, -18]], dtype=int32)

(2) np.cumprod()

求数组中元素的累计积，用法如下：

In [16]:
np.cumprod(arr11)

array([ 4, 12, 24, 24,  0,  0,  0,  0,  0,  0,  0,  0], dtype=int32)

np.min()

np.max()

np.mean()

np.median()

np.var()  #方差

np.std()  #标准差

where()  #该函数相当于Excel中的if函数



In [17]:
arr11

array([[ 4,  3,  2],
       [ 1,  0, -1],
       [-2, -3, -4],
       [-5, -6, -7]])

In [18]:
np.where(arr11<0,'negtive','positive')

array([['positive', 'positive', 'positive'],
       ['positive', 'positive', 'negtive'],
       ['negtive', 'negtive', 'negtive'],
       ['negtive', 'negtive', 'negtive']], dtype='<U8')

3. 线性代数的运算

(1) 重新生成一个数组 arr13:

In [20]:
arr13 = np.array([[1,2,3,5],[2,4,1,6],[1,1,4,3],[2,5,4,1]])
arr13

array([[1, 2, 3, 5],
       [2, 4, 1, 6],
       [1, 1, 4, 3],
       [2, 5, 4, 1]])

(2) linalg库

从Numpy中的linalg库中提取函数，可以对矩阵进行一系列计算。

In [21]:
np.linalg.det(arr13) #求行列式

51.00000000000002

求逆矩阵：

In [22]:
np.linalg.inv(arr13)

array([[-2.23529412,  1.05882353,  1.70588235, -0.29411765],
       [ 0.68627451, -0.25490196, -0.7254902 ,  0.2745098 ],
       [ 0.19607843, -0.21568627,  0.07843137,  0.07843137],
       [ 0.25490196,  0.01960784, -0.09803922, -0.09803922]])

求迹：

In [23]:
np.trace(arr13)

10

求特征向量：

In [24]:
np.linalg.eig(arr13)

(array([11.35035004, -3.99231852, -0.3732631 ,  3.01523159]),
 array([[-0.4754174 , -0.48095078, -0.95004728,  0.19967185],
        [-0.60676806, -0.42159999,  0.28426325, -0.67482638],
        [-0.36135292, -0.16859677,  0.08708826,  0.70663129],
        [-0.52462832,  0.75000995,  0.09497472, -0.07357122]]))

奇异值分解：

In [25]:
np.linalg.svd(arr13)

(array([[-0.50908395,  0.27580803,  0.35260559, -0.73514132],
        [-0.59475561,  0.4936665 , -0.53555663,  0.34020325],
        [-0.39377551, -0.10084917,  0.70979004,  0.57529852],
        [-0.48170545, -0.81856751, -0.29162732, -0.11340459]]),
 array([11.82715609,  4.35052602,  3.17710166,  0.31197297]),
 array([[-0.25836994, -0.52417446, -0.47551003, -0.65755329],
        [-0.10914615, -0.38326507, -0.54167613,  0.74012294],
        [-0.18632462, -0.68784764,  0.69085326,  0.12194478],
        [ 0.94160248, -0.32436807, -0.05655931, -0.07050652]]))

(3) np.dot()

np.dot()函数可以实现矩阵乘积运算，如果需要对两个arr13相乘

矩阵相乘并不是随便两个矩阵就能够实现的，现在定义数组arr14为一个3x4的矩阵，数组arr15为一个4x3的矩阵，使得它们相乘，也就是说，第二个矩阵的行数必须和前一个矩阵的列数相同。结果如下：

In [26]:
arr13

array([[1, 2, 3, 5],
       [2, 4, 1, 6],
       [1, 1, 4, 3],
       [2, 5, 4, 1]])

In [27]:
arr14 = np.array([[1,2,3,5],[2,4,1,6],[1,1,4,3]])
arr15 = np.array([[1,2,3],[2,4,1],[1,1,3],[2,5,4]])

np.dot(arr14,arr15)

array([[18, 38, 34],
       [23, 51, 37],
       [13, 25, 28]])

## .describe()  如a.describe()  、data['Age'].describe()

## .corr() 求相关系数 如 a.corr() 

## .corrwith()可以提取某一变量，查看其与其他变量之间的相关性，如需查看x1与x2、x3之间的相关性
## 如，df.corrwith(df['x1'])

## 3 .cov() 用来计算协方差矩阵

