Numpy是在Python中对一维或多维数组进行运算时常用的计算库。


### 1.利用import导入库，将numpy重命名为np


In [ ]:
import numpy as np


### 2.开始数组的创建

什么是数组呢？在Numpy中有两种数组类型，一种是向量，一种是矩阵。简单来说，向量就是一维数组，矩阵就是二维或多维数组。

（1）一维数组的创建：arange()
在Python中直接用range函数创建数组。并通过type函数查看类型。


In [4]:

lst = range(10)
list(lst)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
lst2 = np.arange(10)
list(lst2)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
type(lst2)

numpy.ndarray

In [15]:
arrl = np.array((1,20,15,18,22))
arr1

array([ 1, 20, 15, 18, 22])

In [16]:
type(arr1)

numpy.ndarray

(2) 二维数组的创建

实则是一种元组套元组，列表套列表的形式，

In [19]:
arr3 = np.array(((1,3,6,6),(5,9,45,21),(27,35,45,76)))
arr3

array([[ 1,  3,  6,  6],
       [ 5,  9, 45, 21],
       [27, 35, 45, 76]])

### 3.一些函数

(1) np.ones() 
创建一个一维数组，里面的元素全部都是1


In [20]:
np.ones(3)

array([1., 1., 1.])

In [21]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [22]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

np.zeros()
利用np.seros()创建一个一维数组，里面的元素都是0：


In [23]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [24]:
np.zeros([3,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

np.empty
函数起到的作用与np.zeros函数类似

In [25]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [26]:
np.empty([3,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])