1.导入Numpy库，重新定义一个数组，这里定义一个列表套列表的数组


In [6]:
import numpy as np
arr4 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

2、一些函数
（1）.shape()

利用 .shape() 函数可以查看数组的形状，输出结果为（3，4），说明arr4是一个三行四列的矩阵，与事实相符。

In [6]:
arr4.shape

(3, 4)

(2).dtype()

利用.dtype()函数可以查看数组的数据类型，返回数组arr4的数据类型为整数型

(3).ravel()和.flatten()

作用：将数组拉平（拉直）。具体用法如下：

In [8]:
a = arr4.ravel()
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [9]:
b = arr4.flatten()
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

表面上看.ravle()和.flatten()函数的作用相同：将数组拉平(拉直）。具体用法如下：

In [10]:
a = arr4.ravel()
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [11]:
b = arr4.flatten()
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

表面上看，.ravel()和.flatten()函数的作用相同，都是将多维数组降成一维数组，但其实.ravel()的返回结果是"视图”形式，.flatten()返回的结果是“拷贝”形式。

在.flatten()下，对b做一些改变，输出结果：

In [12]:
b[0] = 13
b

array([13,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [13]:
arr4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

可以看出，b中的第一个数字变成了13，b发生了改变，而数组arr4没有发生变化。


在.ravel()下，对a做一些改变，输出结果:

In [14]:
a[0] = 13
a

array([13,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [15]:
arr4

array([[13,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

注意到a中的第一个数字同样发生改变，变为13，同时，数组arr4中的第一个数字也跟着变为了13。

因此，可以得出两个函数的区别在于： 用flatten()函数得到的是一个“拷贝”（顾名思义，拷贝当然是一模一样），当b发生变化，原来数组保持原状；而.ravel()返回的是一个”视图“，一旦对1修改，原数组就会发生改变。

（4）.ndim()

.ndim函数将返回数组的维度。输出结果如下：


In [16]:
arr4.ndim

2

(5)  .size

.size函数返回的是数组中元素的个数：

In [17]:
arr4.size

12

(6) .T

In [ ]:
.T是对数组进行转置的函数，具体操作如下：

In [19]:
arr4 = np.array([[13,2,3,4],[5,6,7,8],[9,10,11,12]])
arr4

array([[13,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
arr4.T

array([[13,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

(7) len()

len()函数：查看数组有多少行

In [21]:
len(arr4)

3

(8) np.hstack() 和 np.column_stack()

np.hstack()和np.column_stack()是Numpy中对两个数组进行横向拼接的函数，定义两个数组arr1和arr2,对它们进行拼接：

但必须注意的是：横向拼接要求两个矩阵的行数必须相同。

In [24]:
np.hstack((arr4,arr4))

np.column_stack((arr4,arr4))

array([[13,  2,  3,  4, 13,  2,  3,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8],
       [ 9, 10, 11, 12,  9, 10, 11, 12]])

（9）np.vstack() 和np.row_stack()
是Numpy中对两个数组进行纵向拼接的函数

注意：纵向拼接要求两个矩阵的列数必须相同

In [26]:
np.vstack((arr4,arr4))

np.row_stack((arr4,arr4))

array([[13,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

(10) .reshape() 和 .resize()

是对数组的形状进行再造的两个函数。重新定义一个二维数组arr5。利用.reshape()将数组arr5 重新设置成一个4x6 的二维数组，查看原来的数组arr5,
发现数组arr5没有发生变化，这也是一个"拷贝“的过程



In [29]:
arr5 = np.array(np.arange(24))
arr5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [31]:
c= arr5.reshape(4,6)
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [32]:
arr5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

利用  .resize()修改数组的形状，将 c 改为一个6x4 的二维数组：

需要注意的是，利用 .reshape()函数改变数组形状，原数组不会受到影响，但利用 .resize()函数，原数组会受到影响。因此，常用 。reshape()来对数组形状进行修改

In [33]:
c.resize()
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [34]:
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

3.数组转换


（1） .tolist()
作用是对数组类型进行转变，可以将一个数组类型转换为列表，还是用之前的c为例，先查看c的类型，转换后再查看新的类型，结果显示list


In [35]:
type(c)

numpy.ndarray

In [36]:
d = c.tolist()
d

[[0, 1, 2, 3, 4, 5],
 [6, 7, 8, 9, 10, 11],
 [12, 13, 14, 15, 16, 17],
 [18, 19, 20, 21, 22, 23]]

In [37]:
type(d)

list

(2) .astype()

函数可以转化为数组中每个元素的数据类型


In [38]:
e = c.astype(float)
e

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.]])

In [39]:
e.dtype

dtype('float64')