获取数组中的元素，无非是通过切片和索引的方式。

1. 一维数组元素的获取

（1） 导入Numpy库，并创建一个新的一维数组arr7。数组arr7为由1~10 组成。

In [1]:
import numpy as np

arr7 = np.array(np.arange(1,11))
arr7

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

(2) 索引数组arr7中的第3个元素

In [2]:
arr7[2]

3

由于Python的索引位置是从0算起的，所以当要索引第3个元素时，[]中要输入2.

（3） 索引数组arr7中的前三个元素

In [3]:
arr7[:3]

array([1, 2, 3])

(4) 获取第4个元素及以后的元素

想要获取数组arr7中的第4个及以后元素，[]中的冒号后面不用填任何数字，意在从第4个元素开始进行切片，一直切到最后。

由于Python是“算头不算尾”的，我们要找的第4个元素对应的索引值应该是3，而终止值是默认缺失的，会一直切到最后。


In [ ]:
arr7[3:]

(5) 获取最后两个元素

In [ ]:
arr7[-2:]

(6) 获取数组中的奇数
切片不仅有开始索引值和结束索引值两个参数值，第三个参数位置可以填步长，此时，我们设置步长为2


In [4]:
arr7[::2]

array([1, 3, 5, 7, 9])

2、二维数组元素的获取

（1）重新定义一个数组arr8,构成元素为1~12，并将其重新改组为 3x4 的形式

In [7]:
arr8 = np.array(np.arange(1,13).reshape(3,4))
arr8

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

(2) 提取第二行元素
由于数组arr8中第二行对应的索引值为1，因此，操作如下：



In [8]:
arr8[1]

array([5, 6, 7, 8])

(3) 提取i前两行

In [9]:
arr8[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

(4) 提取第一行和第三行

由于第一行所对应的索引值是0，第三行所对应的索引值是2，在[]中输入参数[0,2]。查看结果：


In [10]:
arr8[[0,2]]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

(5) 提取第一列

提取第一列的意思就是说，要提取每一行中的第一个元素，因此要将每一行都提取出来，然后去掉第一个元素，第一个元素对应的索引值是0。

In [13]:
arr8[:,0]

array([1, 5, 9])

(6) 提取最后两列

In [14]:
arr8[:,-2:]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

(7) 提取指定列中的元素

这里提取第1列和第3列中的元素，首先提取每一行，之后考虑第一列对应的索引值是0，第三列对应的索引值是2，查看结果：



In [15]:
arr8[:,[0,2]]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

(8) 得到数组中的某个元素

需要用两个数字对二维数组中的元素进行定价，比如，我们要得到数组中的数字7所在的位置，应该这样输入：


In [16]:
arr8[1,2]

7

3、布尔索引

我们知道布尔值通常是True/False,现在来用布尔值进行索引。

（1）准备创建一个六行的多维数组，首先要创建一个包含6个布尔值的数组，以便之后的索引，麸质给变量log。创建一个包含6个布尔值的数组，以便之后的索引，赋值给变量log。
创建一个6x4列的新数组arr9,组成元素为1~24.


In [ ]:
log = np.array([True,False,False,True,True,False])


In [18]:
arr9 = np.array(np.arange(1,25).reshape(6,4))
arr9

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

（2）接下来，返回所有为True的对应行，操作如下：


In [24]:
arr9[log]

array([[ 1,  2,  3,  4],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

(3) 布尔索引不仅可以用True/False 表示，也可以用一些字符串来表示，并重新创建一个0~20组成的7x3的新数组arr10

In [27]:
area = np.array(['A','B','A','c','A','B','D'])

In [28]:
obs = np.array(np.arange(21).reshape(7,3))
obs

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

In [ ]:
(4)如果要返回所有的“A"对应的行组成的数组，此时

In [29]:
obs[area=='A'][:,[0,2]]

array([[ 0,  2],
       [ 6,  8],
       [12, 14]])

4、花式索引

就是把数组作为索引，将原数组中的元素提取出来

（1）重新定义一个数组arr10,由1~28构成一个7行4列的二维数组

In [30]:
arr10 = np.arange(1,29).reshape(7,4)
arr10

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28]])

(2) 提取指定行

若想要提取第5行、第2行、第4行、第6行，那么，将这四行对应的索引值找出，分别为4，1，3，5

In [31]:
arr10[[4,1,3,5]]

array([[17, 18, 19, 20],
       [ 5,  6,  7,  8],
       [13, 14, 15, 16],
       [21, 22, 23, 24]])

（3）提取指定列

先指定提取第5行、第2行、第6行，找到它们对应的索引值分别为4，1，5：再提取其中的第1列、第3列、第4列，索引值分别为0，2，3。



In [34]:
arr10[[4,1,5]][:,[0,2,3]]

array([[17, 19, 20],
       [ 5,  7,  8],
       [21, 23, 24]])

(4) 提取指定元素

如果要提取第5行中的第一个元素、第2行中的第2个元素、第4行中的第4个元素、第6行中的第2个元素。首先，找到每一行所对应的索引值为4、1、3、5，在找到每个元素的索引值，分别为0、1、3、1。


In [35]:
arr10[[4,1,3,5],[0,1,3,1]]

array([17,  6, 16, 22])

(5) ix_()

ix()函数能够更简便的完成索引

In [36]:
arr10[np.ix_([4,1,5],[0,2,3])]

array([[17, 19, 20],
       [ 5,  7,  8],
       [21, 23, 24]])